import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import Header from "../components/utilities/Header/Header";
import { motion } from "framer-motion";
import SocialMediaSticky from "@/components/utilities/SocialMediaSticky";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <SocialMediaSticky />
        {children}
      </body>
    </html>
  );
}
